---
title: "Research"
output:
  html_document:
    includes:
      in_header: ga_script.html
      after_body: footer.html
---

<link rel="stylesheet" href="academicons.css"/>
<link rel="stylesheet" href="styles.css" type="text/css">

For a full list of publications, please see my [Google Scholar](https://scholar.google.com/citations?user=6AWzLpgAAAAJ&hl=en) page.

<br>

## Research Areas
My current research focuses on three main areas:

1. The treatment and assessment of Complicated Grief. I serve as the Biostatistician for [The Center for Complicated Grief](https://complicatedgrief.columbia.edu/professionals/complicated-grief-professionals/overview/) at the Columbia School of Social Work. (PI: [M Katherine Shear](https://socialwork.columbia.edu/faculty/full-time/m-katherine-shear/))

2. Assessing the impact of state-level medical and recreational marijuana policies on substance use and other consequences (PI: [Silvia Martins](https://www.mailman.columbia.edu/people/our-faculty/ssm2183)).

3. Assessing the impact of the Affordable Care Act on health insurance and substance use treatment among low income individuals with substance use disorders (PIs: [Mark Olfson](https://www.columbiapsychiatry.org/profile/mark-olfson-md) and [Ramin Mojtabai](https://www.jhsph.edu/faculty/directory/profile/2111/ramin-mojtabai)).

<br>

## Selected Publications
**Mauro C**, Tumasian 3rd R, Skritskaya N, Gacheru M, Zisook S, Simon N, Reynolds CF, Shear MK (2022). The Efficacy of Complicated Grief Therapy for DSM-5-TR Prolonged Grief Disorder. *World Psychiatry*. In Press. [Supplementary Materials](downloads/tables_17.02.2022.pdf)

**Mauro C**, Shear MK, Wang Y (2019). Integrating Multiple-Domain Rules for Disease Classification. *Statistics in Medicine*. 38 (16), 3091-3104. [link to abstract](https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.8173)

<br>
**Mauro C**, Reynolds CF, Maercker A, Skritskaya N, Simon N, Zisook S, Lebowitz B, Cozza S, Shear MK. (2019). Prolonged Grief Disorder: Clinical Utility of ICD-11 Diagnostic Guidelines. *Psychological Medicine*. 49 (5), 861-867 [link to abstract](https://doi.org/10.1017/S0033291718001563)

<br>
**Mauro C**, Newswanger P, Santaella-Tenorio J, Mauro PM, Carline H, Martins SS (2019). Impact of Medical Marijuana Laws on State-Level Marijuana Use by Age and Gender, 2004–2013. *Prevention Science*. 20 (2), 205-214 [link to abstract](https://doi.org/10.1007/s11121-017-0848-3)

*Related Media Coverage:*  

* Mailman School of Public Health [press release](https://www.mailman.columbia.edu/public-health-now/news/more-adults-use-marijuana-states-where-it-legal).  
* [Print Interview](https://medicalresearch.com/author-interviews/what-impact-have-state-level-laws-had-on-marijuana-use/38356/) with MedicalResearch.com.  
* [Radio Interview](downloads/Adolescence and Cannabis.mp3) at News Talk 770 [Calgary Today](https://globalnews.ca/calgary/program/calgary-today/) with Angela Kokott.

<br>
**Mauro C**, Shear MK, Reynolds CF, Simon N, Zisook S, Skritskaya N, Wang Y, Lebowitz B, Duan N, First M, Ghesquiere A, Gribbin C, Glickman K. (2017). Performance characteristics and clinical utility of diagnostic criteria proposals in bereaved treatment-seeking patients. *Psychological Medicine*. 47 (4), 608-615. [link to abstract](https://www.ncbi.nlm.nih.gov/pubmed/27821201)
